Repository nikkolas-james-irwin/vmc-tracking-and-analytics-program, pull requests merged in 2020-10, with the labels that each got.

#6 PR for Issue #5 -- Update README
  README.md
Labels: documentation

#7 Added environment file for conda
  environment.yml
Labels: front-end

#8 Initial Django Framework
  TAP/__init__.py
  TAP/asgi.py
  TAP/settings.py
  TAP/urls.py
  TAP/wsgi.py
  manage.py
  pages/__init__.py
  pages/admin.py
  pages/apps.py
  pages/migrations/__init__.py
  pages/models.py
  pages/static/pages/military_seals1.png
  pages/templates/pages/importPage.html
  pages/templates/pages/landingPage.html
  pages/tests.py
  pages/urls.py
  pages/views.py
Labels: front-end

#20 Issue #19 -- Scanner Data Parser Handle Anonymous Visits
  parsing/scanner_parsing.py
Labels: parser

#23 Issue #22 -- Update Scanner Data Parser and Generator to Include Appointments
  datagen/scanner_generation.py
  parsing/scanner_parsing.py
  parsing/views.py
Labels: parser

#24 Merging updated HTML files with Parser and datagen
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/vmc-tracking-and-analytics-program.iml
  pages/static/pages/CSS/customStyles.css
  pages/static/pages/JS/jquery.slim.min.js
  pages/static/pages/JS/scripts.js
  pages/static/pages/images/military_seals1.png
  pages/templates/pages/base.html
  pages/templates/pages/homePage.html
  pages/templates/pages/importPage.html
  pages/templates/pages/landingPage.html
  pages/templates/pages/visualizationsPage.html
  pages/templates/pages/vmcAdminPage.html
  pages/urls.py
  pages/views.py
Labels: front-end, visualizations
